 export default freelancingProjects = [
    {
        title: "Content Writing Project",
        description: "Write engaging blog posts for a tech blog. Must have experience in the tech industry.",
        accountName: "Bob Brown",
        price: "$150",
    },
    {
        title: "Website Design",
        description: "Design a modern and responsive website for a local bakery.",
        accountName: "Alice Smith",
        price: "$800",
    },
    {
        title: "SEO Optimization",
        description: "Optimize website content for better search engine ranking.",
        accountName: "Charlie Johnson",
        price: "$200",
    },
    {
        title: "Social Media Management",
        description: "Manage social media accounts and create content strategies.",
        accountName: "Dana Lee",
        price: "$300",
    },
    {
        title: "Graphic Design",
        description: "Create a logo and branding materials for a startup company.",
        accountName: "Eva Davis",
        price: "$250",
    },
    {
        title: "Video Editing",
        description: "Edit promotional videos for an online course.",
        accountName: "Frank Harris",
        price: "$400",
    },
    {
        title: "Copywriting",
        description: "Write persuasive copy for a new product launch.",
        accountName: "Grace Martin",
        price: "$180",
    },
    {
        title: "App Development",
        description: "Develop a mobile app for a fitness tracking startup.",
        accountName: "Henry Clark",
        price: "$1200",
    },
    {
        title: "Data Entry",
        description: "Enter data into a spreadsheet for a research project.",
        accountName: "Ivy Lewis",
        price: "$100",
    },
    {
        title: "Virtual Assistance",
        description: "Provide administrative support for a busy entrepreneur.",
        accountName: "Jack Walker",
        price: "$250",
    },
    {
        title: "E-commerce Setup",
        description: "Set up an online store on Shopify for a new business.",
        accountName: "Karen White",
        price: "$600",
    },
    {
        title: "Translation Services",
        description: "Translate website content from English to Spanish.",
        accountName: "Liam King",
        price: "$220",
    },
    {
        title: "Illustration",
        description: "Create custom illustrations for a children's book.",
        accountName: "Mia Scott",
        price: "$350",
    },
    {
        title: "Email Marketing",
        description: "Design and implement an email marketing campaign.",
        accountName: "Noah Green",
        price: "$270",
    },
    {
        title: "Proofreading",
        description: "Proofread and edit a technical document for clarity.",
        accountName: "Olivia Adams",
        price: "$130",
    },
    {
        title: "Podcast Editing",
        description: "Edit and polish podcast episodes for a weekly show.",
        accountName: "Paul Evans",
        price: "$320",
    },
    {
        title: "WordPress Customization",
        description: "Customize a WordPress theme for a blog.",
        accountName: "Quinn Young",
        price: "$500",
    },
    {
        title: "Online Course Creation",
        description: "Create a comprehensive online course on digital marketing.",
        accountName: "Rachel Nelson",
        price: "$900",
    },
    {
        title: "Market Research",
        description: "Conduct market research and provide a detailed report.",
        accountName: "Sam Mitchell",
        price: "$400",
    },
    {
        title: "UX/UI Design",
        description: "Design user interfaces for a new web application.",
        accountName: "Tina Roberts",
        price: "$600",
    },
    {
        title: "Database Management",
        description: "Manage and optimize a SQL database for a retail client.",
        accountName: "Ulysses Collins",
        price: "$700",
    },
    {
        title: "Resume Writing",
        description: "Write a professional resume and cover letter.",
        accountName: "Vera Sanchez",
        price: "$180",
    },
    {
        title: "Photo Retouching",
        description: "Retouch and enhance product photos for an e-commerce site.",
        accountName: "Will Phillips",
        price: "$250",
    },
    {
        title: "Technical Support",
        description: "Provide technical support and troubleshooting for software.",
        accountName: "Xena Rogers",
        price: "$300",
    },
    {
        title: "Blog Management",
        description: "Manage and update content for a lifestyle blog.",
        accountName: "Yara Cox",
        price: "$350",
    },
    {
        title: "Infographic Design",
        description: "Design an infographic to illustrate complex data.",
        accountName: "Zane Bennett",
        price: "$200",
    },
    {
        title: "Custom Illustration",
        description: "Create a custom illustration for a book cover.",
        accountName: "Aiden Brooks",
        price: "$300",
    },
    {
        title: "Product Descriptions",
        description: "Write compelling product descriptions for an online store.",
        accountName: "Bella Sanders",
        price: "$220",
    },
    {
        title: "Press Release Writing",
        description: "Write a press release for a company announcement.",
        accountName: "Cameron Bennett",
        price: "$250",
    },
    {
        title: "Chatbot Development",
        description: "Develop a chatbot for customer service on a website.",
        accountName: "Devin Ward",
        price: "$500",
    },
    {
        title: "Brand Strategy",
        description: "Develop a brand strategy and positioning plan.",
        accountName: "Ella Murphy",
        price: "$800",
    },
    {
        title: "Sales Copywriting",
        description: "Write sales copy for a new marketing campaign.",
        accountName: "Felix Cooper",
        price: "$220",
    },
    {
        title: "User Testing",
        description: "Conduct user testing and provide feedback on a new app.",
        accountName: "Gina Foster",
        price: "$300",
    },
    {
        title: "Event Planning",
        description: "Plan and coordinate a virtual business event.",
        accountName: "Hank Murphy",
        price: "$600",
    },
    {
        title: "Voice Over",
        description: "Record voice-over for an animated explainer video.",
        accountName: "Iris Lee",
        price: "$350",
    },
    {
        title: "Social Media Ads",
        description: "Create and manage social media ads for increased engagement.",
        accountName: "Jake Foster",
        price: "$400",
    },
    {
        title: "Product Photography",
        description: "Take high-quality photos of products for an e-commerce website.",
        accountName: "Kara Nelson",
        price: "$300",
    },
    {
        title: "Website Copywriting",
        description: "Write persuasive website copy for a corporate site.",
        accountName: "Leo Johnson",
        price: "$250",
    },
    {
        title: "Logo Animation",
        description: "Create an animated version of a company logo.",
        accountName: "Mona Reed",
        price: "$350",
    },
    {
        title: "App UI Design",
        description: "Design user interfaces for a mobile app.",
        accountName: "Nina Collins",
        price: "$600",
    },
    {
        title: "Technical Writing",
        description: "Write technical manuals and guides for software products.",
        accountName: "Oscar Davis",
        price: "$400",
    },
    {
        title: "PDF Form Creation",
        description: "Create interactive PDF forms for data collection.",
        accountName: "Penny Green",
        price: "$180",
    },
    {
        title: "Sales Funnel Design",
        description: "Design a sales funnel for a digital marketing campaign.",
        accountName: "Quentin Adams",
        price: "$500",
    },
    {
        title: "Video Animation",
        description: "Create animated explainer videos for a new service.",
        accountName: "Riley Clark",
        price: "$700",
    },
    {
        title: "Web Scraping",
        description: "Develop a web scraper to collect data from various sites.",
        accountName: "Samantha Lee",
        price: "$400",
    },
    {
        title: "Brochure Design",
        description: "Design a tri-fold brochure for a local event.",
        accountName: "Tom Roberts",
        price: "$250",
    },
    {
        title: "Landing Page Design",
        description: "Design a high-converting landing page for a product launch.",
        accountName: "Ursula Wright",
        price: "$300",
    },
    {
        title: "Interactive Quiz",
        description: "Create an interactive quiz for a website.",
        accountName: "Victor Moore",
        price: "$350",
    },
    {
        title: "Sales Page Copy",
        description: "Write engaging sales page copy for an online course.",
        accountName: "Wendy Hill",
        price: "$200",
    },
    {
        title: "Website Audit",
        description: "Perform a comprehensive audit of a website's performance.",
        accountName: "Xander Green",
        price: "$450",
    }
];
